{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "7ae04cd2-4386-4d78-be00-60ceda8aa8ad",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "✅ Model, Scaler, and Feature Columns Loaded Successfully!\n",
      " * Serving Flask app '__main__'\n",
      " * Debug mode: on\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.\n",
      " * Running on http://127.0.0.1:5000\n",
      "Press CTRL+C to quit\n",
      " * Restarting with watchdog (windowsapi)\n"
     ]
    },
    {
     "ename": "SystemExit",
     "evalue": "1",
     "output_type": "error",
     "traceback": [
      "An exception has occurred, use %tb to see the full traceback.\n",
      "\u001b[1;31mSystemExit\u001b[0m\u001b[1;31m:\u001b[0m 1\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\Admin\\AppData\\Local\\anaconda3\\New folder\\Lib\\site-packages\\IPython\\core\\interactiveshell.py:3561: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.\n",
      "  warn(\"To exit: use 'exit', 'quit', or Ctrl-D.\", stacklevel=1)\n"
     ]
    }
   ],
   "source": [
    "# -------------------------------\n",
    "# app.py — Manufacturing Equipment Output Prediction Web App\n",
    "# -------------------------------\n",
    "\n",
    "from flask import Flask, request, render_template_string\n",
    "import pickle\n",
    "import json\n",
    "import numpy as np\n",
    "\n",
    "# Initialize Flask app\n",
    "app = Flask(__name__)\n",
    "\n",
    "# -------------------------------\n",
    "# Load Model, Scaler, and Features\n",
    "# -------------------------------\n",
    "with open(\"linear_regression_model.pkl\", \"rb\") as f:\n",
    "    model = pickle.load(f)\n",
    "\n",
    "with open(\"scaler.pkl\", \"rb\") as f:\n",
    "    scaler = pickle.load(f)\n",
    "\n",
    "with open(\"feature_columns.json\", \"r\") as f:\n",
    "    feature_columns = json.load(f)\n",
    "\n",
    "print(\"✅ Model, Scaler, and Feature Columns Loaded Successfully!\")\n",
    "\n",
    "# -------------------------------\n",
    "# HTML Template (Embedded)\n",
    "# -------------------------------\n",
    "HTML_PAGE = \"\"\"\n",
    "<!DOCTYPE html>\n",
    "<html>\n",
    "<head>\n",
    "    <title>Manufacturing Equipment Output Prediction</title>\n",
    "    <style>\n",
    "        body {\n",
    "            background-color: #f3f0ff;\n",
    "            font-family: Arial, sans-serif;\n",
    "            text-align: center;\n",
    "            padding: 30px;\n",
    "        }\n",
    "        form {\n",
    "            background: white;\n",
    "            padding: 25px;\n",
    "            border-radius: 12px;\n",
    "            display: inline-block;\n",
    "            box-shadow: 0 0 15px rgba(0,0,0,0.15);\n",
    "        }\n",
    "        input {\n",
    "            margin: 8px;\n",
    "            padding: 8px;\n",
    "            border-radius: 5px;\n",
    "            border: 1px solid #ccc;\n",
    "            width: 200px;\n",
    "        }\n",
    "        button {\n",
    "            background-color: #6a5acd;\n",
    "            color: white;\n",
    "            padding: 10px 18px;\n",
    "            border: none;\n",
    "            border-radius: 5px;\n",
    "            cursor: pointer;\n",
    "            margin-top: 10px;\n",
    "        }\n",
    "        button:hover {\n",
    "            background-color: #5a4abd;\n",
    "        }\n",
    "        h2 {\n",
    "            color: #4b0082;\n",
    "        }\n",
    "    </style>\n",
    "</head>\n",
    "<body>\n",
    "    <h2>Manufacturing Equipment Output Prediction</h2>\n",
    "    <form action=\"/predict\" method=\"post\">\n",
    "        {% for col in feature_columns %}\n",
    "        <div>\n",
    "            <label>{{ col }}:</label>\n",
    "            <input type=\"text\" name=\"{{ col }}\" placeholder=\"Enter {{ col }}\">\n",
    "        </div>\n",
    "        {% endfor %}\n",
    "        <br>\n",
    "        <button type=\"submit\">Predict</button>\n",
    "    </form>\n",
    "    {% if prediction_text %}\n",
    "        <h3 style=\"color:green;\">{{ prediction_text }}</h3>\n",
    "    {% endif %}\n",
    "</body>\n",
    "</html>\n",
    "\"\"\"\n",
    "\n",
    "# -------------------------------\n",
    "# Routes\n",
    "# -------------------------------\n",
    "@app.route('/')\n",
    "def home():\n",
    "    return render_template_string(HTML_PAGE, feature_columns=feature_columns)\n",
    "\n",
    "@app.route('/predict', methods=['POST'])\n",
    "def predict():\n",
    "    try:\n",
    "        # Collect input values from form\n",
    "        input_data = [float(request.form.get(col, 0)) for col in feature_columns]\n",
    "\n",
    "        # Scale and predict\n",
    "        input_scaled = scaler.transform([input_data])\n",
    "        prediction = model.predict(input_scaled)[0]\n",
    "\n",
    "        return render_template_string(\n",
    "            HTML_PAGE,\n",
    "            feature_columns=feature_columns,\n",
    "            prediction_text=f\"Predicted Equipment Output: {prediction:.2f}\"\n",
    "        )\n",
    "\n",
    "    except Exception as e:\n",
    "        return render_template_string(\n",
    "            HTML_PAGE,\n",
    "            feature_columns=feature_columns,\n",
    "            prediction_text=f\"Error: {str(e)}\"\n",
    "        )\n",
    "\n",
    "# -------------------------------\n",
    "# Run Flask App\n",
    "# -------------------------------\n",
    "if __name__ == '__main__':\n",
    "    app.run(debug=True)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "fef7a1a0-61e9-4731-b23c-1f45b32a4ad0",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
